### ISSUE TITLE
BS react role is missing in server updates message in #get-your-roles channel

### ISSUE THREAD

**Issue by mourya96** [sinsniwal/iitm-server-bot#10]
![image](https://github.com/sinsniwal/iitm-server-bot/assets/39103437/bf64fb44-0c77-425e-9cfc-e46a2dada8e7)
Please add the role for the BS level since few people have completed the BSc level.

**Comment by sinsniwal** [comment]
Added a reaction role for BS which can be taken along with the BSc role.
