### ISSUE TITLE
Move to Google OAuth for verification

### ISSUE THREAD

**Issue by lmaotrigine** [sinsniwal/iitm-server-bot#17]
Following discussion in the server, I think replacing the current email verification system with Google OAuth is the right way forward. Whether we use multiple OAuth or not is a point of contention, but for now keeping user experience in mind, we can send an ephemeral link message to a web application.

This basically requires removing the Modal logic, and just have one persistent view. This should be implemented without having to use the raw `on_interaction` event which Discord has refused to acknowledge the drawbacks of.

I'm self assigning this for now, and will get to it next week depending on my other workload. In the meantime, if someone wants to pick this up, feel free to. However please mention this issue in your commit messages/PR content so that I am kept in the loop.

**Comment by droxtal** [comment]
What if I am willing to check my email & its spam folder. And I want to use email based verification?

**Comment by lmaotrigine** [comment]
you might be, but the majority of people find the email thing annoying
and oauth2 is more elegant and secured and gives us infrastructure for potential interaction with the google API should the need arise. the decision to switch to OAuth over email has already been finalized. 

If you have any objections based on concrete examples where it provides a worse user experience or similar, feel free to elaborate.

**Comment by droxtal** [comment]
I don't have any objection. I was just suggesting to not completely purge the email system.

Most of the websites I have seen haven't purged the email sign up option in favor OAuth. And I think we too shouldn't.

![image](https://github.com/sinsniwal/iitm-server-bot/assets/125192278/8198e7fe-ed1c-4655-a4c8-7f8d7e49824a)

![image](https://github.com/sinsniwal/iitm-server-bot/assets/125192278/d4dec2ca-72d2-455f-8ec6-6fe730748129)

![image](https://github.com/sinsniwal/iitm-server-bot/assets/125192278/3782038f-5cd4-4aa1-a960-615481c4e716)

![image](https://github.com/sinsniwal/iitm-server-bot/assets/125192278/fcea88bf-06c0-4113-b50b-cd64a7429551)

![image](https://github.com/sinsniwal/iitm-server-bot/assets/125192278/232886b2-5e0c-47ad-a241-0c80b1a1d3b5)

**Comment by lmaotrigine** [comment]
these are all examples of what we are not. we don't allow signing up with random emails. we want to verify an email provided by Google, hence OAuth. 

as i said this discussion has already taken place and implementations are underway. you can bring up any concerns you have in the server.

**Comment by lmaotrigine** [comment]
closing as this has been sniped.
