### ISSUE TITLE
Ephemeral message should inform the existence of a discord user with the email.

### ISSUE THREAD

**Issue by droxtal** [sinsniwal/iitm-server-bot#18]
This message is sent even if the email has already been verified by another Discord user.
![image](https://github.com/sinsniwal/iitm-server-bot/assets/125192278/7fbf4069-f62e-4c61-b2b5-8a7ad2179da8)

Instead the message should be -
```
Your email is already linked with another Discord user <discord id>.
Please contact admins if this was not you. Someone might be impersonating you.

To link your current ID with the email, simply leave the server from the previous ID & then verify using the current one.
```

**Comment by lmaotrigine** [comment]
This will be superseded by #17 
moreover, you don't need to leave the server to link another account, see cogs/verification.py

**Comment by sinsniwal** [comment]
> This message is sent even if the email has already been verified by another Discord user. ![image](https://user-images.githubusercontent.com/125192278/244939826-7fbf4069-f62e-4c61-b2b5-8a7ad2179da8.png)
> 
> Instead the message should be -
> 
> ```
> Your email is already linked with another Discord user <discord id>.
> Please contact admins if this was not you. Someone might be impersonating you.
> 
> To link your current ID with the email, simply leave the server from the previous ID & then verify using the current one.
> ```

If an email ID has been previously used for verification by another account, we still allow the user to verify again. If the verification is successful, we remove the roles of the previous user and assign them to the current user.
