### ISSUE TITLE
Verification using multiple accounts with the same email id

### ISSUE THREAD

**Issue by sankarannamboodiri** [sinsniwal/iitm-server-bot#35]
People are able to verify using multiple accounts using the same email id

**Comment by IndraReddy5** [comment]
it takes out old user roles right...?

**Comment by sankarannamboodiri** [comment]
No it doesnt take out old user's roles.

**Comment by sinsniwal** [comment]
Yes, you are correct; I am shifting the database and will crosscheck all the new users before merging the database. I am thinking of doing that this weekend.

**Comment by sankarannamboodiri** [comment]
Ok cool

**Comment by sankarannamboodiri** [comment]
Issue resolved
